### ISSUE TITLE
Windows builds failing because of gitpython dependency

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#137]
Applying the patches from Phabricator currently fails because of a broken dependency in the latest docker containers:
```
C:\ws\workspace\amd64_windows_vs2017\llvm-project>python C:\ws\workspace\amd64_windows_vs2017/llvm-premerge-checks/scripts/phabtalk/apply_patch2.py --comment-file C:\ws\workspace\amd64_windows_vs2017/build/.phabricator-comment  --token **** --url https://reviews.llvm.org 245836 
Traceback (most recent call last):
  File "C:\ws\workspace\amd64_windows_vs2017/llvm-premerge-checks/scripts/phabtalk/apply_patch2.py", line 26, in <module>
    from git import Repo, GitCommandError
  File "C:\Python38\lib\site-packages\git\__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "C:\Python38\lib\site-packages\git\exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "C:\Python38\lib\site-packages\git\compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

So i disabled the build feedback in Phabricator:
https://reviews.llvm.org/harbormaster/step/view/4/

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by ChristianKuehnel** [comment]
@Harmon758 thx for looking into this. Upgrading gitpython to 3.0.6 solves the problem.
