### ISSUE TITLE
Can't apply patch ("No such file or directory")

### ISSUE THREAD

**Issue by joker-eph** [google/llvm-premerge-checks#203]
This revision https://reviews.llvm.org/D82276 indicates a build failure, here is the BuildKite log: https://buildkite.com/llvm-project/diff-checks/builds/1429#6f186bef-b7fd-4f3a-bee4-b3ca2aa5bb1e

Relevant excerpt: 

```
$ ./scripts/buildkite/apply_patch.sh
--
  | repository exist, will reuse
  | working dir /mnt/disks/ssd0/agent/llvm-project-fork
  | Syncing local, origin and upstream...
  | refresh of master branch completed
  | Getting dependencies of 272303
  | Base revision is fb9f9dc318d62788885a122aaee9dcd4272e87b1
  | git reset, git cleanup...
  | Analyzing D82276
  | Applying diff 272303 for revision D82276...
  | Traceback (most recent call last):
  | File "scripts/phabtalk/apply_patch2.py", line 331, in <module>
  | patcher.run()
  | File "scripts/phabtalk/apply_patch2.py", line 124, in run
  | self._apply_diff(self.diff_id, revision_id)
  | File "scripts/phabtalk/apply_patch2.py", line 240, in _apply_diff
  | raise Exception('Applying patch failed:\n{}'.format(proc.stdout + proc.stderr))
  | Exception: Applying patch failed:
  | error: i/llvm/cmake/modules/VersionFromVCS.cmake: No such file or directory
```

The file llvm/cmake/modules/VersionFromVCS.cmake has been in the repo "forever", the "base revision" indicated (fb9f9dc318d62788885a122aaee9dcd4272e87b1)  is the current HEAD

**Comment by metaflow** [comment]
Looking on the debug output: phabricator reported that diff is

```
diff --git a/i/llvm/cmake/modules/VersionFromVCS.cmake b/llvm/cmake/modules/VersionFromVCS.cmake

--- a/i/llvm/cmake/modules/VersionFromVCS.cmake

+++ b/llvm/cmake/modules/VersionFromVCS.cmake

@@ -4,7 +4,7 @@

 # extra argument, otherwise uses CMAKE_CURRENT_SOURCE_DIR).

 

 function(get_source_info path revision repository)

-  find_package(Git)

+  find_package(Git QUIET)

   if(GIT_FOUND)

     execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --git-dir

       WORKING_DIRECTORY ${path}

@@ -45,5 +45,7 @@

         set(${repository} ${path} PARENT_SCOPE)

       endif()

     endif()

+  else()

+    message(WARNING "Git not found. Version cannot be determined.")

   endif()

 endfunction()
```

and `i/llvm/cmake/modules/VersionFromVCS.cmake` does not exists. @joker-eph maybe you know where this `i/` is coming from?

**Comment by metaflow** [comment]
It looks like such errors are caused by the patches created against local changes (e.g. one of the multiple commit). #260 Improves error reporting and provides a possible fix to upload a diff with all local changes included.
