### ISSUE TITLE
[libcxx] Generated output step is failing because of IndentationError

### ISSUE THREAD

**Issue by chaitanyav** [google/llvm-premerge-checks#442]
```
Traceback (most recent call last):

  File "/home/libcxx-builder/.buildkite-agent/builds/google-libcxx-builder-libcxx-precommit-ci-group-41qd-1/llvm-project/libcxx-ci/libcxx/utils/generate_header_tests.py", line 154, in <module>

    main()

  File "/home/libcxx-builder/.buildkite-agent/builds/google-libcxx-builder-libcxx-precommit-ci-group-41qd-1/llvm-project/libcxx-ci/libcxx/utils/generate_header_tests.py", line 149, in main

    produce(test.joinpath('libcxx/private_headers.verify.cpp'), variables)

  File "/home/libcxx-builder/.buildkite-agent/builds/google-libcxx-builder-libcxx-precommit-ci-group-41qd-1/llvm-project/libcxx-ci/libcxx/utils/generate_header_tests.py", line 111, in produce

    result = execute_script(script, variables)

  File "/home/libcxx-builder/.buildkite-agent/builds/google-libcxx-builder-libcxx-precommit-ci-group-41qd-1/llvm-project/libcxx-ci/libcxx/utils/generate_header_tests.py", line 88, in execute_script

    code = compile(script, 'fake-filename', 'exec')

  File "fake-filename", line 16

    if header.startswith('__pstl'):

    ^

IndentationError: expected an indented block after 'if' statement on line 13
```
Relevant links:
https://buildkite.com/llvm-project/libcxx-ci/builds/22671#0187a3b9-87f0-40a3-ba10-be1bd2344a69

**Screenshots**
![image](https://user-images.githubusercontent.com/75975/233637529-1b051f5f-8bcf-4076-8bcd-f07fe7f5c499.png)
![image](https://user-images.githubusercontent.com/75975/233637650-231c0972-a7b2-48bc-9346-ab61ab0eb736.png)

**Comment by metaflow** [comment]
@mstorsjo could you please take a look?

**Comment by mstorsjo** [comment]
Probably fixed by https://github.com/llvm-premerge-tests/llvm-project/commit/1702ff3d12b9e292a122da206dae71a4ecd87506
