### ISSUE TITLE
retry on failure to communicate with Phabricator in patch script

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#97]
If `apply_patch.py` is unable to connect to Phabricator it just fails:
```
+ python3 /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/llvm-premerge-checks/scripts/phabtalk/apply_patch.py --comment-file /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/build/.phabricator-comment
Traceback (most recent call last):
  File "/mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/llvm-premerge-checks/scripts/phabtalk/apply_patch.py", line 125, in <module>
    patcher.run()
  File "/mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/llvm-premerge-checks/scripts/phabtalk/apply_patch.py", line 56, in run
    self.phab.update_interfaces()
  File "/usr/local/lib/python3.7/dist-packages/phabricator/__init__.py", line 400, in update_interfaces
    interfaces = query()
  File "/usr/local/lib/python3.7/dist-packages/phabricator/__init__.py", line 248, in __call__
    return self._request(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/phabricator/__init__.py", line 309, in _request
    response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

Add some wait-and-retry logic there before failing.
Also: Make sure this produces an error message in Phabricator.

Revision: https://reviews.llvm.org/D72692
Build: https://jenkins.llvm-merge-guard.org/job/amd64_debian_testing_clang8/1144/

**Comment by ChristianKuehnel** [comment]
fixed via #121
